## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Создать вектор размера 10, заполненный единицами

In [6]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Создать вектор размера 10, заполненный числом 2.5

In [7]:
np.full((1,10),2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [27]:
a = np.zeros((1,10))
a[0, 4] = 1
print(a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


Развернуть вектор (первый становится последним)

In [26]:
b = a[:,::-1]
print(b)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [28]:
def f1(i,j):
    return 3*i+j
np.fromfunction(f1, (3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [33]:
c = np.array([1,2,0,0,4,0])
print(c)
indx = (c > 0)
print(c[c>0])

[1 2 0 0 4 0]
[1 2 4]


Создать 3x3 единичную матрицу

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [36]:
np.random.random((3,3,3))

array([[[0.34290652, 0.75678902, 0.69234676],
        [0.03908263, 0.45790114, 0.65876298],
        [0.05057722, 0.89867541, 0.96650889]],

       [[0.81503544, 0.47755716, 0.45454496],
        [0.17765302, 0.88451337, 0.9450696 ],
        [0.89214563, 0.54616842, 0.8863668 ]],

       [[0.8054912 , 0.3456513 , 0.97030057],
        [0.93920726, 0.28645301, 0.86956682],
        [0.94732494, 0.24210177, 0.7569809 ]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [38]:
np.sum(np.random.random((1,30)))/30

0.49393827938472495

Перемножить матрицы 5x3 и 3x2

In [41]:
d = np.random.random((5,3))
e = np.random.random((3,2))
np.dot(d,e)

array([[0.62458571, 0.89303346],
       [0.6737849 , 0.70601091],
       [0.40294675, 0.30172822],
       [0.30364812, 0.33077079],
       [0.36164657, 0.26198988]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [43]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [44]:
f = np.random.random(20)
f[f.argmax()] = 0
print(f)

[0.26186929 0.29711626 0.51841896 0.59845685 0.01369789 0.70633305
 0.70444878 0.86745666 0.38910655 0.03827453 0.22763249 0.33058742
 0.08223451 0.89602788 0.09140816 0.80984763 0.         0.03349838
 0.38631851 0.97213583]


Преобразовать массив из float в int

In [47]:
g = np.arange(10, dtype=np.float32)
g = g.astype(np.int32, copy=False)
print(g)

[0 1 2 3 4 5 6 7 8 9]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [50]:
import scipy.spatial

h = np.random.random((10,2))
j = scipy.spatial.distance.cdist(h,h)

[[0.         0.54093335 0.46775571 0.72852392 0.66514702 0.227508
  0.55023098 0.35131666 0.25798144 0.80919168]
 [0.54093335 0.         0.63204164 0.75617954 0.56440452 0.34699253
  0.00933088 0.82728191 0.47911471 0.26906324]
 [0.46775571 0.63204164 0.         0.26745022 0.29442161 0.56018626
  0.63794526 0.40813284 0.22828079 0.82645724]
 [0.72852392 0.75617954 0.26745022 0.         0.21247088 0.78519746
  0.75929805 0.65268287 0.4754984  0.8799488 ]
 [0.66514702 0.56440452 0.29442161 0.21247088 0.         0.66118045
  0.56628505 0.69780924 0.41094084 0.6685161 ]
 [0.227508   0.34699253 0.56018626 0.78519746 0.66118045 0.
  0.35615941 0.56994442 0.33440864 0.61358219]
 [0.55023098 0.00933088 0.63794526 0.75929805 0.56628505 0.35615941
  0.         0.83591753 0.48693517 0.2597328 ]
 [0.35131666 0.82728191 0.40813284 0.65268287 0.69780924 0.56994442
  0.83591753 0.         0.36841994 1.08019027]
 [0.25798144 0.47911471 0.22828079 0.4754984  0.41094084 0.33440864
  0.48693517 0.3684199

Случайно расположить p элементов в 2D массив

In [57]:
n = 10
p = 4
k = np.zeros((n, n))
np.put(k, np.random.choice(range(n*n), p, replace=False), 1)
print(k)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [59]:
l = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(l) + (len(l) - 1) * 3)
result[::4] = l
print(result)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [61]:
o = np.random.randint(0,10,50)
print(np.bincount(o).argmax())

1


Найти n наибольших значений в массиве

In [64]:
p = np.random.randint(0,10, 50)
print(p)
n = 5;
print(p[np.argpartition(-p,n)[:n]])

[1 9 1 0 3 0 2 3 9 8 9 6 6 5 8 3 8 1 1 1 9 5 0 4 4 7 8 0 4 5 7 0 8 8 5 3 2
 3 3 8 0 6 6 7 8 4 0 2 2 4]
[9 9 9 9 8]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

Посмотреть первые 5 записей

Сколько наблюдений в наборе данных?


Сколько столбцов в наборе данных?

Напечатайте все названия столбцов

Какое название у 105 столбца?

Какой тип наблюдений в 105 столбце?

Как проиндексирован набор данных?

Каково значение имени продукта в 19-м наблюдении?

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?