## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Создать вектор размера 10, заполненный единицами

In [6]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Создать вектор размера 10, заполненный числом 2.5

In [7]:
np.full((1,10),2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [27]:
a = np.zeros((1,10))
a[0, 4] = 1
print(a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


Развернуть вектор (первый становится последним)

In [26]:
b = a[:,::-1]
print(b)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [28]:
def f1(i,j):
    return 3*i+j
np.fromfunction(f1, (3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [33]:
c = np.array([1,2,0,0,4,0])
print(c)
indx = (c > 0)
print(c[c>0])

[1 2 0 0 4 0]
[1 2 4]


Создать 3x3 единичную матрицу

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [36]:
np.random.random((3,3,3))

array([[[0.34290652, 0.75678902, 0.69234676],
        [0.03908263, 0.45790114, 0.65876298],
        [0.05057722, 0.89867541, 0.96650889]],

       [[0.81503544, 0.47755716, 0.45454496],
        [0.17765302, 0.88451337, 0.9450696 ],
        [0.89214563, 0.54616842, 0.8863668 ]],

       [[0.8054912 , 0.3456513 , 0.97030057],
        [0.93920726, 0.28645301, 0.86956682],
        [0.94732494, 0.24210177, 0.7569809 ]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [38]:
np.sum(np.random.random((1,30)))/30

0.49393827938472495

Перемножить матрицы 5x3 и 3x2

In [41]:
d = np.random.random((5,3))
e = np.random.random((3,2))
np.dot(d,e)

array([[0.62458571, 0.89303346],
       [0.6737849 , 0.70601091],
       [0.40294675, 0.30172822],
       [0.30364812, 0.33077079],
       [0.36164657, 0.26198988]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [43]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [44]:
f = np.random.random(20)
f[f.argmax()] = 0
print(f)

[0.26186929 0.29711626 0.51841896 0.59845685 0.01369789 0.70633305
 0.70444878 0.86745666 0.38910655 0.03827453 0.22763249 0.33058742
 0.08223451 0.89602788 0.09140816 0.80984763 0.         0.03349838
 0.38631851 0.97213583]


Преобразовать массив из float в int

In [47]:
g = np.arange(10, dtype=np.float32)
g = g.astype(np.int32, copy=False)
print(g)

[0 1 2 3 4 5 6 7 8 9]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [50]:
import scipy.spatial

h = np.random.random((10,2))
j = scipy.spatial.distance.cdist(h,h)

[[0.         0.54093335 0.46775571 0.72852392 0.66514702 0.227508
  0.55023098 0.35131666 0.25798144 0.80919168]
 [0.54093335 0.         0.63204164 0.75617954 0.56440452 0.34699253
  0.00933088 0.82728191 0.47911471 0.26906324]
 [0.46775571 0.63204164 0.         0.26745022 0.29442161 0.56018626
  0.63794526 0.40813284 0.22828079 0.82645724]
 [0.72852392 0.75617954 0.26745022 0.         0.21247088 0.78519746
  0.75929805 0.65268287 0.4754984  0.8799488 ]
 [0.66514702 0.56440452 0.29442161 0.21247088 0.         0.66118045
  0.56628505 0.69780924 0.41094084 0.6685161 ]
 [0.227508   0.34699253 0.56018626 0.78519746 0.66118045 0.
  0.35615941 0.56994442 0.33440864 0.61358219]
 [0.55023098 0.00933088 0.63794526 0.75929805 0.56628505 0.35615941
  0.         0.83591753 0.48693517 0.2597328 ]
 [0.35131666 0.82728191 0.40813284 0.65268287 0.69780924 0.56994442
  0.83591753 0.         0.36841994 1.08019027]
 [0.25798144 0.47911471 0.22828079 0.4754984  0.41094084 0.33440864
  0.48693517 0.3684199

Случайно расположить p элементов в 2D массив

In [57]:
n = 10
p = 4
k = np.zeros((n, n))
np.put(k, np.random.choice(range(n*n), p, replace=False), 1)
print(k)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [59]:
l = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(l) + (len(l) - 1) * 3)
result[::4] = l
print(result)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [61]:
o = np.random.randint(0,10,50)
print(np.bincount(o).argmax())

1


Найти n наибольших значений в массиве

In [64]:
p = np.random.randint(0,10, 50)
print(p)
n = 5;
print(p[np.argpartition(-p,n)[:n]])

[1 9 1 0 3 0 2 3 9 8 9 6 6 5 8 3 8 1 1 1 9 5 0 4 4 7 8 0 4 5 7 0 8 8 5 3 2
 3 3 8 0 6 6 7 8 4 0 2 2 4]
[9 9 9 9 8]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [ ]:
import pandas as pd
food = pd.DataFrame.read_csv('en.openfoodfacts.org.products.tsv', sep='\t')


Посмотреть первые 5 записей

In [41]:
food[0:5]
food.head(5)

url  \
code                                                               
0000000003087  http://world-en.openfoodfacts.org/product/0000...   
0000000004530  http://world-en.openfoodfacts.org/product/0000...   
0000000004559  http://world-en.openfoodfacts.org/product/0000...   
0000000016087  http://world-en.openfoodfacts.org/product/0000...   
0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                                  creator   created_t      created_datetime  \
code                                                                          
0000000003087  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
0000000004530             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000004559             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
0000000016087             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
0000000016094             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

              last_modified_t last_modified_datetime  \
code                                                   
0000000003087      1474103893   2016-09-17T09:18:13Z   
0000000004530      1489069957   2017-03-09T14:32:37Z   
0000000004559      1489069957   2017-03-09T14:32:37Z   
0000000016087      1489055731   2017-03-09T10:35:31Z   
0000000016094      1489055653   2017-03-09T10:34:13Z   

                                 product_name generic_name quantity packaging  \
code                                                                            
0000000003087              Farine de blé noir          NaN      1kg       NaN   
0000000004530  Banana Chips Sweetened (Whole)          NaN      NaN       NaN   
0000000004559                         Peanuts          NaN      NaN       NaN   
0000000016087          Organic Salted Nut Mix          NaN      NaN       NaN   
0000000016094                 Organic Polenta          NaN      NaN       NaN   

                      ...         fruits-vegetables-nuts_100g  \
code                  ...                                       
0000000003087         ...                                 NaN   
0000000004530         ...                                 NaN   
0000000004559         ...                                 NaN   
0000000016087         ...                                 NaN   
0000000016094         ...                                 NaN   

              fruits-vegetables-nuts-estimate_100g  \
code                                                 
0000000003087                                  NaN   
0000000004530                                  NaN   
0000000004559                                  NaN   
0000000016087                                  NaN   
0000000016094                                  NaN   

              collagen-meat-protein-ratio_100g cocoa_100g chlorophyl_100g  \
code                                                                        
0000000003087                              NaN        NaN             NaN   
0000000004530                              NaN        NaN             NaN   
0000000004559                              NaN        NaN             NaN   
0000000016087                              NaN        NaN             NaN   
0000000016094                              NaN        NaN             NaN   

              carbon-footprint_100g nutrition-score-fr_100g  \
code                                                          
0000000003087                   NaN                     NaN   
0000000004530                   NaN                    14.0   
0000000004559                   NaN                     0.0   
0000000016087                   NaN                    12.0   
0000000016094                   NaN                     NaN   

              nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
code                                                                           
0000000003087                     NaN                 NaN                 NaN  
000000000453

Сколько наблюдений в наборе данных?


In [24]:
len(food.axes[0])
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [25]:
len(food.axes[1])
food.shape[1]

162

Напечатайте все названия столбцов

In [12]:
food.columns

Index(['url', 'creator', 'created_t', 'created_datetime', 'last_modified_t',
       'last_modified_datetime', 'product_name', 'generic_name', 'quantity',
       'packaging',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=162)

Какое название у 105 столбца?

In [20]:
food.columns[104]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [31]:
food[food.columns[104]].dtype


dtype('float64')

Как проиндексирован набор данных?

In [32]:
food.index

Index(['0000000003087', '0000000004530', '0000000004559', '0000000016087',
       '0000000016094', '0000000016100', '0000000016117', '0000000016124',
       '0000000016193', '0000000016513',
       ...
            '99111250',          '9918', '9935010000003',      '99410148',
       '9948282780603',      '99567453', '9970229501521', '9977471758307',
       '9980282863788',  '999990026839'],
      dtype='object', name='code', length=356027)

Каково значение имени продукта в 19-м наблюдении?

In [36]:
food['product_name'][18]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [38]:
import io
import requests
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_table(url)

Как много продуктов стоят более чем $10.00?

chipo[chipo.columns[4]].dtype

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [76]:
chipo.loc[:, ['item_name', 'item_price']]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17                          Chicken Burrito     $8.49 
18                              Canned Soda     $2.18 
19                             Chicken Bowl     $8.75 
20                      Chips and Guacamole     $4.45 
21                         Barbacoa Burrito     $8.99 
22                         Nantucket Nectar     $3.39 
23                          Chicken Burrito    $10.98 
24                                     Izze     $3.39 
25             Chips and Fresh Tomato Salsa     $2.39 
26                             Chicken Bowl     $8.49 
27                         Carnitas Burrito     $8.99 
28                              Canned Soda     $1.09 
29                          Chicken Burrito     $8.49 
...                                     ...        ...
4592                       Barbacoa Burrito    $11.75 
4593                          Carnitas Bowl    $11.75 
4594                          Barbacoa Bowl    $11.75 
4595                           Chicken Bowl     $8.75 
4596                    Chips and Guacamole     $4.45 
4597                      Canned Soft Drink     $1.25 
4598                          Bottled Water     $1.50 
4599                           Chicken Bowl     $8.75 
4600                    Chips and Guacamole     $4.45 
4601                      Canned Soft Drink     $1.25 
4602                       Barbacoa Burrito     $9.25 
4603                       Barbacoa Burrito     $9.25 
4604                           Chicken Bowl     $8.75 
4605                    Chips and Guacamole     $4.45 
4606                      Canned Soft Drink     $1.25 
4607                          Steak Burrito    $11.75 
4608                         Veggie Burrito    $11.25 
4609                      Canned Soft Drink     $1.25 
4610                          Steak Burrito    $11.75 
4611                         Veggie Burrito    $11.25 
4612                          Carnitas Bowl     $9.25 
4613                                  Chips     $2.15 
4614                          Bottled Water     $1.50 
4615                     Chicken Soft Tacos     $8.75 
4616                    Chips and Guacamole     $4.45 
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [78]:
chipo.sort_values(by='item_name')

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [121]:
chipo.drop_puplicates('item_name')





AttributeError: 'DataFrame' object has no attribute 'drop_puplicates'

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [90]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].sum().2


18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [101]:
canned = chipo[chipo['item_name'] == 'Canned Soda']
canned[canned['quantity'] > 1].count().quantity

20