## Numpy

Импортировать NumPy под именем np

In [3]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Создать вектор размера 10, заполненный единицами

In [6]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Создать вектор размера 10, заполненный числом 2.5

In [7]:
np.full((1,10),2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [27]:
zeros_vector_with_one = np.zeros((1,10))
zeros_vector_with_one[0, 4] = 1
print(zeros_vector_with_one)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


Развернуть вектор (первый становится последним)

In [26]:
inv_zeros_vector_with_one = zeros_vector_with_one[:,::-1]
print(inv_zeros_vector_with_one)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [28]:
def f1(i,j):
    return 3*i+j
np.fromfunction(f1, (3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [47]:
vect = np.array([1,2,0,0,4,0])
np.where(vect > 0)[0]

array([0, 1, 4])

Создать 3x3 единичную матрицу

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [36]:
np.random.random((3,3,3))

array([[[0.34290652, 0.75678902, 0.69234676],
        [0.03908263, 0.45790114, 0.65876298],
        [0.05057722, 0.89867541, 0.96650889]],

       [[0.81503544, 0.47755716, 0.45454496],
        [0.17765302, 0.88451337, 0.9450696 ],
        [0.89214563, 0.54616842, 0.8863668 ]],

       [[0.8054912 , 0.3456513 , 0.97030057],
        [0.93920726, 0.28645301, 0.86956682],
        [0.94732494, 0.24210177, 0.7569809 ]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [38]:
np.sum(np.random.random((1,30)))/30

0.49393827938472495

Перемножить матрицы 5x3 и 3x2

In [48]:
matrix_5x3 = np.random.random((5,3))
matrix_3x2 = np.random.random((3,2))
np.dot(matrix_5x3,matrix_3x2)

array([[0.25132542, 0.4667806 ],
       [0.7455346 , 0.64539128],
       [0.5102855 , 0.61495966],
       [0.46375931, 0.32430171],
       [0.58251391, 0.64244416]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [43]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [54]:
random_vector = np.random.random(20)
random_vector[random_vector.argmax()] = 0
print(random_vector)

[0.91913978 0.42033758 0.28228541 0.94690647 0.89848267 0.59872603
 0.9166645  0.37820828 0.21369914 0.5166743  0.51471569 0.32121997
 0.04544877 0.94512307 0.65299254 0.64821854 0.9108468  0.37182936
 0.         0.3577273 ]


Преобразовать массив из float в int

In [55]:
arange_vect = np.arange(10, dtype=np.float32)
arange_vect = arange_vect.astype(np.int32, copy=False)
print(arange_vect)

[0 1 2 3 4 5 6 7 8 9]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [58]:
import scipy.spatial

random_vector_2 = np.random.random((10,2))
scipy.spatial.distance.cdist(random_vector_2,random_vector_2)

array([[0.        , 0.75172722, 0.5857194 , 0.98522083, 0.74223616,
        0.84193042, 0.35467021, 0.22025438, 0.30945359, 0.36679185],
       [0.75172722, 0.        , 0.543189  , 0.28045882, 0.32221345,
        0.7493673 , 0.61383313, 0.54273324, 0.815069  , 1.00231629],
       [0.5857194 , 0.543189  , 0.        , 0.61182355, 0.28654523,
        0.28330286, 0.73448719, 0.51778581, 0.42486871, 0.62137749],
       [0.98522083, 0.28045882, 0.61182355, 0.        , 0.32541819,
        0.71729017, 0.89053013, 0.79293007, 0.98045019, 1.17905431],
       [0.74223616, 0.32221345, 0.28654523, 0.32541819, 0.        ,
        0.43218019, 0.75798554, 0.59207977, 0.67556381, 0.87613954],
       [0.84193042, 0.7493673 , 0.28330286, 0.71729017, 0.43218019,
        0.        , 1.01763503, 0.79897187, 0.61326616, 0.78122281],
       [0.35467021, 0.61383313, 0.73448719, 0.89053013, 0.75798554,
        1.01763503, 0.        , 0.22764824, 0.63237693, 0.72128916],
       [0.22025438, 0.54273324, 0.5177858

Случайно расположить p элементов в 2D массив

In [59]:
n = 10
p = 4
zeros_nxn = np.zeros((n, n))
np.put(zeros_nxn, np.random.choice(range(n*n), p, replace=False), 1)
print(zeros_nxn)

[[0. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [60]:
vector = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(vector) + (len(vector) - 1) * 3)
result[::4] = vector
print(result)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [63]:
random_int = np.random.randint(0,10,50)
print(np.bincount(random_int).argmax())

5


Найти n наибольших значений в массиве

In [64]:
random_int_2 = np.random.randint(0,10,50)
print(random_int_2)
n = 5;
print(random_int_2[np.argpartition(-random_int_2,n)[:n]])

[9 0 2 5 8 4 5 4 5 7 9 3 4 0 9 1 9 7 8 9 0 0 5 6 1 7 6 9 4 2 2 9 9 3 4 2 8
 7 9 9 1 2 5 6 5 9 3 5 2 5]
[9 9 9 9 9]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [1]:
import pandas as pd
food = pd.read_csv('en.openfoodfacts.org.products.tsv', sep='\t')


/home/dexus/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [3]:
food[0:5]
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [4]:
len(food.axes[0])
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [5]:
len(food.axes[1])
food.shape[1]

163

Напечатайте все названия столбцов

In [6]:
food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [7]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [8]:
food[food.columns[104]].dtype


dtype('float64')

Как проиндексирован набор данных?

In [9]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [10]:
food['product_name'][18]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [11]:
import io
import requests
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_table(url)

Как много продуктов стоят более чем $10.00?

In [65]:
drop_dup_1 = chipo.drop_duplicates('item_name')
convert = drop_dup_1['item_price'].apply(lambda x: float(x[1:]))
convert[convert > 10].count()

13

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [66]:
drop_dup_2 = chipo.drop_duplicates('item_name')
drop_dup_2.loc[:, ['item_name', 'item_price']]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
16                          Chicken Burrito     $8.49 
18                              Canned Soda     $2.18 
21                         Barbacoa Burrito     $8.99 
27                         Carnitas Burrito     $8.99 
33                            Carnitas Bowl     $8.99 
34                            Bottled Water     $1.09 
38    Chips and Tomatillo Green Chili Salsa     $2.95 
39                            Barbacoa Bowl    $11.75 
40                                    Chips     $2.15 
44                       Chicken Salad Bowl     $8.75 
54                               Steak Bowl     $8.99 
56                      Barbacoa Soft Tacos     $9.25 
57                           Veggie Burrito    $11.25 
62                              Veggie Bowl    $11.25 
92                       Steak Crispy Tacos     $9.25 
111     Chips and Tomatillo Red Chili Salsa     $2.95 
168                   Barbacoa Crispy Tacos    $11.75 
186                       Veggie Salad Bowl    $11.25 
191      Chips and Roasted Chili-Corn Salsa     $2.39 
233      Chips and Roasted Chili Corn Salsa     $2.95 
237                     Carnitas Soft Tacos     $9.25 
250                           Chicken Salad    $10.98 
263                       Canned Soft Drink     $1.25 
281                        Steak Salad Bowl    $23.78 
298                       6 Pack Soft Drink     $6.49 
300     Chips and Tomatillo-Red Chili Salsa     $2.39 
445                                    Bowl    $22.20 
510                                 Burrito     $7.40 
520                            Crispy Tacos     $7.40 
554                   Carnitas Crispy Tacos     $9.25 
664                             Steak Salad     $8.99 
674       Chips and Mild Fresh Tomato Salsa     $3.00 
738                       Veggie Soft Tacos    $11.25 
1132                    Carnitas Salad Bowl    $11.89 
1229                    Barbacoa Salad Bowl    $11.89 
1414                                  Salad     $7.40 
1653                    Veggie Crispy Tacos     $8.49 
1694                           Veggie Salad     $8.49 
3750                         Carnitas Salad     $8.99

Отсортировать по имени предмета

In [15]:
chipo.sort_values(by='item_name')

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [68]:
drop_dup_3 = chipo.drop_duplicates('item_name')
convert_2 = drop_dup_2['item_price'].apply(lambda x: float(x[1:]))
chipo[chipo['item_name'] == chipo['item_name'][convert_2.argmax()]].sum().quantity



/home/dexus/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: 'argmax' is deprecated, use 'idxmax' instead. The behavior of 'argmax'
will be corrected to return the positional maximum in the future.
Use 'series.values.argmax' to get the position of the maximum now.
  This is separate from the ipykernel package so we can avoid doing imports until


31

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [69]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].sum().quantity


18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [70]:
canned = chipo[chipo['item_name'] == 'Canned Soda']
canned[canned['quantity'] > 1].count().quantity

20